#!/bin/bash
set -e

##############################################################################
##
##  Precommit hook which runs against staged files.
##
##  Usually used but not limited to lint and code formatters.
##  Insert your custom logic at the end of the script
##
##############################################################################


## restore MERGE HEAD
restoreMergeHead() {
    if [[ -n "$MERGE_HEAD_REF" ]]; then
        echo "Restoring merge information"
        echo "$MERGE_HEAD_REF" > .git/MERGE_HEAD
        echo "$MERGE_MSG_CONTENT" > .git/MERGE_MSG
    fi
}

###
#  Stashes local changes and reapplies them after all checks
###
# save staged files
reapplyUnstagedFiles() {
    echo "Restoring unstaged files"
    STASH_NUM=$(git stash list | grep "$STASH_NAME" | sed -E 's/stash@\{(.*)\}.*/\1/')

    if [[ -n "$STASH_NUM" ]]; then
        # don't run it with -q as it is broken in git 2.24.3 preinstalled on macOS
        # Was fixed in 2.25
        git stash pop stash@\{"$STASH_NUM"\}
    fi

    git status

    restoreMergeHead
}

git status

# save merge head when it exists
if [ -f .git/MERGE_HEAD ]; then
    echo "Detected a merge commit, saving merge information"
    MERGE_HEAD_REF=$(cat .git/MERGE_HEAD)
    MERGE_MSG_CONTENT=$(cat .git/MERGE_MSG)
    rm .git/MERGE_HEAD
    rm .git/MERGE_MSG
fi

# do a fake commit to save all staged files
git commit --no-verify -F .git/COMMIT_EDITMSG

COMMIT_STATUS=$?
if [ $COMMIT_STATUS -eq 0 ]; then
    git status
    echo "Saving unstaged files before running pre-commit checks"

    # stash all unstaged files
    STASH_NAME=pre-commit-$(date +%s)
    git stash save --include-untracked "$STASH_NAME"

    git status

    # undo fake commit, restore staged files
    # repo is now in the same state as the commit which is about to be made.
    # Ready for pre-commit checks
    git reset --soft HEAD~1
    git status

    # executes on script exit in success and error case
    trap reapplyUnstagedFiles EXIT
else
    echo "no unstaged files"
    restoreMergeHead
fi

###
#  Write your pre-commit logic here
###

echo "Running pre-commit checks"

# TODO format source code
# dartfmt -w -l 120 lib
# go fmt .

# TODO run lint
# flutter analyze
# eslint lib/**

git status
